import type { Tool } from './types'

export const TOOLS: Tool[] = [
  // ── Version Control ────────────────────────────────────────────────────────
  {
    id: 'git',
    name: 'Git',
    description: 'Distributed version control system',
    category: 'version-control',
    platforms: ['windows', 'macos', 'linux'],
    version: '2.45+',
    size: '50 MB',
    icon: '🔀',
    verifyCommand: 'git --version',
    wingetId: 'Git.Git',
    brewId: 'git',
    aptId: 'git',
    installers: {
      windows: 'installers/windows/install-git.ps1',
      macos: 'installers/macos/install-git.sh',
      linux: 'installers/linux/install-git.sh',
    },
  },
  {
    id: 'github-desktop',
    name: 'GitHub Desktop',
    description: 'Visual Git/GitHub interface',
    category: 'version-control',
    platforms: ['windows', 'macos'],
    version: '3.x',
    size: '150 MB',
    icon: '🖥️',
    verifyCommand: 'powershell -NoProfile -Command "if(Test-Path ($env:LOCALAPPDATA+\'\\GitHubDesktop\\Update.exe\')){\'installed\'}else{exit 1}"',
    wingetId: 'GitHub.GitHubDesktop',
    installers: {
      windows: 'installers/windows/install-github-desktop.ps1',
      macos: 'installers/macos/install-github-desktop.sh',
    },
  },
  {
    id: 'git-lfs',
    name: 'Git LFS',
    description: 'Large File Storage for Git',
    category: 'version-control',
    platforms: ['windows', 'macos', 'linux'],
    version: '3.4+',
    size: '40 MB',
    icon: '📦',
    verifyCommand: 'git lfs version',
    wingetId: 'GitHub.GitLFS',
    brewId: 'git-lfs',
    aptId: 'git-lfs',
    dependsOn: ['git'],
    installers: {
      windows: 'installers/windows/install-git-lfs.ps1',
      macos: 'installers/macos/install-git-lfs.sh',
      linux: 'installers/linux/install-git-lfs.sh',
    },
  },
  // ── Runtime & Languages ────────────────────────────────────────────────────
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'JavaScript/TypeScript runtime',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '20 LTS',
    size: '200 MB',
    icon: '🟢',
    verifyCommand: 'node --version',
    wingetId: 'OpenJS.NodeJS.LTS',
    brewId: 'node',
    aptId: 'nodejs',
    installers: {
      windows: 'installers/windows/install-nodejs.ps1',
      macos: 'installers/macos/install-nodejs.sh',
      linux: 'installers/linux/install-nodejs.sh',
    },
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Python programming language',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '3.12+',
    size: '100 MB',
    icon: '🐍',
    verifyCommand: 'python --version',
    wingetId: 'Python.Python.3.12',
    brewId: 'python',
    aptId: 'python3',
    installers: {
      windows: 'installers/windows/install-python.ps1',
      macos: 'installers/macos/install-python.sh',
      linux: 'installers/linux/install-python.sh',
    },
  },
  {
    id: 'golang',
    name: 'Go Lang',
    description: 'Go programming language',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.21+',
    size: '300 MB',
    icon: '🐹',
    verifyCommand: 'go version',
    wingetId: 'GoLang.Go',
    brewId: 'go',
    aptId: 'golang',
    installers: {
      windows: 'installers/windows/install-golang.ps1',
      macos: 'installers/macos/install-golang.sh',
      linux: 'installers/linux/install-golang.sh',
    },
  },
  {
    id: 'rust',
    name: 'Rust',
    description: 'Rust programming language & Cargo',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.75+',
    size: '150 MB',
    icon: '🦀',
    verifyCommand: 'rustc --version',
    wingetId: 'Rustlang.Rustup',
    brewId: 'rustup',
    installers: {
      windows: 'installers/windows/install-rust.ps1',
      macos: 'installers/macos/install-rust.sh',
      linux: 'installers/linux/install-rust.sh',
    },
  },
  {
    id: 'deno',
    name: 'Deno',
    description: 'Modern TypeScript/JavaScript runtime',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.40+',
    size: '100 MB',
    icon: '🦕',
    verifyCommand: 'deno --version',
    wingetId: 'DenoLand.Deno',
    brewId: 'deno',
    installers: {
      windows: 'installers/windows/install-deno.ps1',
      macos: 'installers/macos/install-deno.sh',
      linux: 'installers/linux/install-deno.sh',
    },
  },
  {
    id: 'bun',
    name: 'Bun',
    description: 'Ultra-fast JavaScript runtime',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.0+',
    size: '80 MB',
    icon: '🍞',
    verifyCommand: 'bun --version',
    wingetId: 'Oven-sh.Bun',
    brewId: 'bun',
    installers: {
      windows: 'installers/windows/install-bun.ps1',
      macos: 'installers/macos/install-bun.sh',
      linux: 'installers/linux/install-bun.sh',
    },
  },
  {
    id: 'java',
    name: 'Java (JDK)',
    description: 'Java Development Kit',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '21.0+',
    size: '500 MB',
    icon: '☕',
    verifyCommand: 'java --version',
    wingetId: 'EclipseAdoptium.Temurin.21.JDK',
    brewId: 'temurin@21',
    aptId: 'temurin-21-jdk',
    installers: {
      windows: 'installers/windows/install-java.ps1',
      macos: 'installers/macos/install-java.sh',
      linux: 'installers/linux/install-java.sh',
    },
  },
  // ── Package Managers ───────────────────────────────────────────────────────
  {
    id: 'yarn',
    name: 'Yarn',
    description: 'Alternative Node.js package manager',
    category: 'package-manager',
    platforms: ['windows', 'macos', 'linux'],
    version: '4.0+',
    size: '30 MB',
    icon: '🧶',
    verifyCommand: 'yarn --version',
    dependsOn: ['nodejs'],
    installers: {
      windows: 'installers/windows/install-yarn.ps1',
      macos: 'installers/macos/install-yarn.sh',
      linux: 'installers/linux/install-yarn.sh',
    },
  },
  {
    id: 'maven',
    name: 'Maven',
    description: 'Java build & dependency manager',
    category: 'package-manager',
    platforms: ['windows', 'macos', 'linux'],
    version: '3.9+',
    size: '50 MB',
    icon: '🪶',
    verifyCommand: 'mvn --version',
    wingetId: 'Apache.Maven',
    brewId: 'maven',
    aptId: 'maven',
    dependsOn: ['java'],
    installers: {
      windows: 'installers/windows/install-maven.ps1',
      macos: 'installers/macos/install-maven.sh',
      linux: 'installers/linux/install-maven.sh',
    },
  },
  {
    id: 'gradle',
    name: 'Gradle',
    description: 'Alternative Java build tool',
    category: 'package-manager',
    platforms: ['windows', 'macos', 'linux'],
    version: '8.5+',
    size: '100 MB',
    icon: '🐘',
    verifyCommand: 'gradle --version',
    wingetId: 'Gradle.Gradle',
    brewId: 'gradle',
    aptId: 'gradle',
    dependsOn: ['java'],
    installers: {
      windows: 'installers/windows/install-gradle.ps1',
      macos: 'installers/macos/install-gradle.sh',
      linux: 'installers/linux/install-gradle.sh',
    },
  },
  {
    id: 'homebrew',
    name: 'Homebrew',
    description: 'macOS package manager',
    category: 'package-manager',
    platforms: ['macos'],
    version: '4.1+',
    size: '50 MB',
    icon: '🍺',
    verifyCommand: 'brew --version',
    installers: {
      macos: 'installers/macos/install-homebrew.sh',
    },
  },
  // ── Editors & IDEs ─────────────────────────────────────────────────────────
  {
    id: 'vscode',
    name: 'VSCode',
    description: 'Advanced & lightweight code editor',
    category: 'editor',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.87+',
    size: '350 MB',
    icon: '💙',
    verifyCommand: 'code --version',
    wingetId: 'Microsoft.VisualStudioCode',
    brewId: 'visual-studio-code',
    installers: {
      windows: 'installers/windows/install-vscode.ps1',
      macos: 'installers/macos/install-vscode.sh',
      linux: 'installers/linux/install-vscode.sh',
    },
  },
  // ── CLI & Development ──────────────────────────────────────────────────────
  {
    id: 'claude-cli',
    name: 'Claude CLI',
    description: 'Claude command-line interface',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '0.1+',
    size: '30 MB',
    icon: '🤖',
    verifyCommand: 'claude --version',
    dependsOn: ['nodejs'],
    installers: {
      windows: 'installers/windows/install-claude-cli.ps1',
      macos: 'installers/macos/install-claude-cli.sh',
      linux: 'installers/linux/install-claude-cli.sh',
    },
  },
  {
    id: 'codex-cli',
    name: 'Codex CLI',
    description: 'Codex integration CLI',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.0+',
    size: '25 MB',
    icon: '⚡',
    verifyCommand: 'codex --version',
    dependsOn: ['nodejs'],
    installers: {
      windows: 'installers/windows/install-codex-cli.ps1',
      macos: 'installers/macos/install-codex-cli.sh',
      linux: 'installers/linux/install-codex-cli.sh',
    },
  },
  {
    id: 'rtk',
    name: 'RTK',
    description: 'CLI proxy that reduces LLM token usage 60-90% on dev commands',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '0.39+',
    size: '4 MB',
    icon: '🦀',
    verifyCommand: 'rtk --version',
    brewId: 'rtk',
    installers: {
      windows: 'installers/windows/install-rtk.ps1',
      macos: 'installers/macos/install-rtk.sh',
      linux: 'installers/linux/install-rtk.sh',
    },
  },
  {
    id: 'github-cli',
    name: 'GitHub CLI',
    description: 'Official GitHub command-line tool',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '2.92+',
    size: '35 MB',
    icon: 'GH',
    verifyCommand: 'gh --version',
    wingetId: 'GitHub.cli',
    brewId: 'gh',
    aptId: 'gh',
    dependsOn: ['git'],
    installers: {
      windows: 'installers/windows/install-github-cli.ps1',
      macos: 'installers/macos/install-github-cli.sh',
      linux: 'installers/linux/install-github-cli.sh',
    },
  },
  // ── Databases ──────────────────────────────────────────────────────────────
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    description: 'Advanced relational database',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '16.0+',
    size: '400 MB',
    icon: '🐘',
    verifyCommand: 'psql --version',
    wingetId: 'PostgreSQL.PostgreSQL',
    brewId: 'postgresql',
    aptId: 'postgresql',
    installers: {
      windows: 'installers/windows/install-postgresql.ps1',
      macos: 'installers/macos/install-postgresql.sh',
      linux: 'installers/linux/install-postgresql.sh',
    },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'Document-oriented NoSQL database',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '7.0+',
    size: '500 MB',
    icon: '🍃',
    verifyCommand: 'mongod --version',
    wingetId: 'MongoDB.Server',
    brewId: 'mongodb-community',
    installers: {
      windows: 'installers/windows/install-mongodb.ps1',
      macos: 'installers/macos/install-mongodb.sh',
      linux: 'installers/linux/install-mongodb.sh',
    },
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'In-memory cache/session database',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '7.2+',
    size: '50 MB',
    icon: '🔴',
    verifyCommand: 'redis-cli --version',
    installers: {
      windows: 'installers/windows/install-redis.ps1',
      macos: 'installers/macos/install-redis.sh',
      linux: 'installers/linux/install-redis.sh',
    },
  },
  // ── DevOps & Containers ────────────────────────────────────────────────────
  {
    id: 'docker',
    name: 'Docker',
    description: 'Containerization platform',
    category: 'devops',
    platforms: ['windows', 'macos', 'linux'],
    version: '25.0+',
    size: '500 MB',
    icon: '🐳',
    verifyCommand: 'docker --version',
    wingetId: 'Docker.DockerDesktop',
    brewId: 'docker',
    aptId: 'docker-ce',
    installers: {
      windows: 'installers/windows/install-docker.ps1',
      macos: 'installers/macos/install-docker.sh',
      linux: 'installers/linux/install-docker.sh',
    },
  },
  {
    id: 'docker-compose',
    name: 'Docker Compose',
    description: 'Multi-container orchestration',
    category: 'devops',
    platforms: ['windows', 'macos', 'linux'],
    version: '2.25+',
    size: '50 MB',
    icon: '🐙',
    verifyCommand: 'docker compose version',
    dependsOn: ['docker'],
    installers: {
      windows: 'installers/windows/install-docker-compose.ps1',
      macos: 'installers/macos/install-docker-compose.sh',
      linux: 'installers/linux/install-docker-compose.sh',
    },
  },
  // ── Testing & API ──────────────────────────────────────────────────────────
  {
    id: 'postman',
    name: 'Postman',
    description: 'API testing & development platform',
    category: 'testing',
    platforms: ['windows', 'macos', 'linux'],
    version: '12.0+',
    size: '400 MB',
    icon: '📮',
    wingetId: 'Postman.Postman',
    brewId: 'postman',
    verifyCommand: 'powershell -NoProfile -Command "$p=Join-Path $env:LOCALAPPDATA \'Postman\'; $e=Join-Path $p \'Postman.exe\'; if (Test-Path $e) { (Get-Item $e).VersionInfo.FileVersion } else { exit 1 }"',
    installers: {
      windows: 'installers/windows/install-postman.ps1',
      macos: 'installers/macos/install-postman.sh',
      linux: 'installers/linux/install-postman.sh',
    },
  },

  // ── System Libraries ───────────────────────────────────────────────────────
  {
    id: 'vcredist-2008',
    name: 'VC++ 2008 Redist',
    description: 'Microsoft Visual C++ 2008 Redistributable (x86) — required for PHP 5.3/5.4 on WampServer',
    category: 'system',
    platforms: ['windows'],
    version: '9.0+',
    size: '4 MB',
    icon: '🔧',
    verifyCommand: 'powershell -NoProfile -Command "Get-Package \'Microsoft Visual C++ 2008*\' -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Version"',
    installers: { windows: 'installers/windows/install-vcredist-2008.ps1' },
  },
  {
    id: 'vcredist-all',
    name: 'All VC++ Redistributables',
    description: 'All Visual C++ Redistributable Packages x86 + x86_x64 (2005–2022) — required by WampServer',
    category: 'system',
    platforms: ['windows'],
    version: '2008–2022',
    size: '60 MB',
    icon: '📦',
    verifyCommand: 'powershell -NoProfile -Command "if ((Get-Package \'Microsoft Visual C++ 2008*\' -ErrorAction SilentlyContinue) -and (Get-Package \'Microsoft Visual C++ 2015-2022*\' -ErrorAction SilentlyContinue)) { \'installed\' } else { exit 1 }"',
    installers: { windows: 'installers/windows/install-vcredist-all.ps1' },
  },
  {
    id: 'vcredist-2010',
    name: 'VC++ 2010 Redist',
    description: 'Microsoft Visual C++ 2010 Redistributable (x86 + x64)',
    category: 'system',
    platforms: ['windows'],
    version: '10.0+',
    size: '15 MB',
    icon: '🔧',
    verifyCommand: 'powershell -NoProfile -Command "Get-Package \'Microsoft Visual C++ 2010*\' -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Version"',
    installers: { windows: 'installers/windows/install-vcredist-2010.ps1' },
  },
  {
    id: 'vcredist-2012',
    name: 'VC++ 2012 Redist',
    description: 'Microsoft Visual C++ 2012 Redistributable (x86 + x64)',
    category: 'system',
    platforms: ['windows'],
    version: '11.0+',
    size: '12 MB',
    icon: '🔧',
    verifyCommand: 'powershell -NoProfile -Command "Get-Package \'Microsoft Visual C++ 2012*\' -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Version"',
    installers: { windows: 'installers/windows/install-vcredist-2012.ps1' },
  },
  {
    id: 'vcredist-2013',
    name: 'VC++ 2013 Redist',
    description: 'Microsoft Visual C++ 2013 Redistributable (x86 + x64)',
    category: 'system',
    platforms: ['windows'],
    version: '12.0+',
    size: '12 MB',
    icon: '🔧',
    verifyCommand: 'powershell -NoProfile -Command "Get-Package \'Microsoft Visual C++ 2013*\' -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Version"',
    installers: { windows: 'installers/windows/install-vcredist-2013.ps1' },
  },
  {
    id: 'vcredist-2015-2022',
    name: 'VC++ 2015-2022 Redist',
    description: 'Microsoft Visual C++ 2015-2022 Redistributable (x86 + x64) — required by WampServer',
    category: 'system',
    platforms: ['windows'],
    version: '14.0+',
    size: '25 MB',
    icon: '🔧',
    verifyCommand: 'powershell -NoProfile -Command "Get-Package \'Microsoft Visual C++ 2015-2022*\' -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty Version"',
    installers: { windows: 'installers/windows/install-vcredist-2015-2022.ps1' },
  },

  // ── Web Server (WampServer) ────────────────────────────────────────────────
  {
    id: 'wampserver',
    name: 'WampServer',
    description: 'Windows web dev environment: Apache + PHP + MySQL/MariaDB + PhpMyAdmin',
    category: 'web-server',
    platforms: ['windows'],
    version: '3.4.0',
    size: '500 MB',
    icon: '🟠',
    verifyCommand: 'powershell -NoProfile -Command "if ((Test-Path \'C:\\wamp64\\wampmanager.exe\') -and (Test-Path \'C:\\wamp64\\bin\\apache\')) { $v=(Get-Item \'C:\\wamp64\\wampmanager.exe\').VersionInfo.ProductVersion; if ($v) { $v } else { \'3.x\' } } else { exit 1 }"',
    dependsOn: ['vcredist-all'],
    installers: { windows: 'installers/windows/install-wampserver.ps1' },
  },
  {
    id: 'apache',
    name: 'Apache HTTP Server',
    description: 'Apache 2.4 web server (WampServer addon)',
    category: 'web-server',
    platforms: ['windows'],
    version: '2.4.67',
    size: '10 MB',
    icon: '🪶',
    verifyCommand: 'powershell -NoProfile -Command "$f=Get-ChildItem \'C:\\wamp64\\bin\\apache\\apache2.4*\\bin\\httpd.exe\' -ErrorAction SilentlyContinue|Sort-Object FullName -Descending|Select-Object -First 1; if($f){& $f.FullName -v 2>&1|Select-Object -First 1}else{exit 1}"',
    dependsOn: ['wampserver'],
    installers: { windows: 'installers/windows/install-apache-wamp.ps1' },
  },
  {
    id: 'php',
    name: 'PHP',
    description: 'PHP scripting language — standalone or WampServer addon',
    category: 'web-server',
    platforms: ['windows', 'macos', 'linux'],
    version: '8.5+',
    size: '30 MB',
    icon: '🐘',
    verifyCommand: 'php --version',
    installers: {
      windows: 'installers/windows/install-php.ps1',
      macos: 'installers/macos/install-php.sh',
      linux: 'installers/linux/install-php.sh',
    },
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'MySQL relational database (standalone or WampServer addon)',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '8.0+',
    size: '300 MB',
    icon: '🐬',
    verifyCommand: 'mysql --version',
    wingetId: 'Oracle.MySQL',
    brewId: 'mysql',
    aptId: 'mysql-server',
    installers: {
      windows: 'installers/windows/install-mysql.ps1',
      macos: 'installers/macos/install-mysql.sh',
      linux: 'installers/linux/install-mysql.sh',
    },
  },
  {
    id: 'mysql-workbench',
    name: 'MySQL Workbench',
    description: 'Visual GUI tool for MySQL database design, administration and querying',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '8.0+',
    size: '60 MB',
    icon: '🗂️',
    wingetId: 'Oracle.MySQLWorkbench',
    brewId: 'mysqlworkbench',
    verifyCommand: 'powershell -NoProfile -Command "$r=Get-ItemProperty HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\*,HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\* -ErrorAction SilentlyContinue | Where-Object {$_.DisplayName -like \'MySQL Workbench*\'} | Select-Object -First 1; if ($r) { $r.DisplayVersion } else { exit 1 }"',
    installers: {
      windows: 'installers/windows/install-mysql-workbench.ps1',
      macos: 'installers/macos/install-mysql-workbench.sh',
      linux: 'installers/linux/install-mysql-workbench.sh',
    },
  },
  {
    id: 'sqlserver-express',
    name: 'SQL Server Express',
    description: 'Microsoft SQL Server Express 2022 — free relational database for Windows',
    category: 'database',
    platforms: ['windows'],
    version: '2022',
    size: '1.5 GB',
    icon: '🔷',
    wingetId: 'Microsoft.SQLServer.2022.Express',
    verifyCommand: 'powershell -NoProfile -Command "$svc=Get-Service -Name MSSQL* -ErrorAction SilentlyContinue | Select-Object -First 1; if ($svc) { $svc.DisplayName } else { exit 1 }"',
    installers: { windows: 'installers/windows/install-sqlserver.ps1' },
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    description: 'MariaDB relational database — MySQL-compatible (standalone or WampServer addon)',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '11.4+',
    size: '250 MB',
    icon: '🦭',
    verifyCommand: 'mariadb --version',
    wingetId: 'MariaDB.Server',
    brewId: 'mariadb',
    aptId: 'mariadb-server',
    installers: {
      windows: 'installers/windows/install-mariadb.ps1',
      macos: 'installers/macos/install-mariadb.sh',
      linux: 'installers/linux/install-mariadb.sh',
    },
  },
  {
    id: 'phpmyadmin',
    name: 'PhpMyAdmin',
    description: 'Web-based MySQL/MariaDB administration tool (WampServer addon)',
    category: 'web-server',
    platforms: ['windows'],
    version: '5.2.3',
    size: '20 MB',
    icon: '🗄️',
    verifyCommand: 'powershell -NoProfile -Command "if (Test-Path \'C:\\wamp64\\apps\\phpmyadmin*\') { \'installed\' } else { exit 1 }"',
    dependsOn: ['wampserver'],
    installers: { windows: 'installers/windows/install-phpmyadmin.ps1' },
  },
  {
    id: 'adminer',
    name: 'Adminer',
    description: 'Lightweight database management web UI (WampServer addon)',
    category: 'web-server',
    platforms: ['windows'],
    version: '4.8.1',
    size: '1 MB',
    icon: '🔍',
    verifyCommand: 'powershell -NoProfile -Command "if((Test-Path \'C:\\wamp64\\apps\\adminer*\')-or(Test-Path \'C:\\wamp64\\alias\\adminer*\')){\'installed\'}else{exit 1}"',
    dependsOn: ['wampserver'],
    installers: { windows: 'installers/windows/install-adminer.ps1' },
  },
  {
    id: 'xdebug',
    name: 'xDebug',
    description: 'PHP debugging and profiling extension',
    category: 'web-server',
    platforms: ['windows', 'macos', 'linux'],
    version: '3.5.1',
    size: '2 MB',
    icon: '🐛',
    verifyCommand: 'php -r "if(!extension_loaded(\'xdebug\')){exit(1);}echo phpversion(\'xdebug\');"',
    dependsOn: ['php'],
    installers: {
      windows: 'installers/windows/install-xdebug.ps1',
      macos: 'installers/macos/install-xdebug.sh',
      linux: 'installers/linux/install-xdebug.sh',
    },
  },
]

export const CATEGORY_LABELS: Record<string, string> = {
  'version-control': '🔀 Version Control & Git',
  'runtime':         '🚀 Runtime & Languages',
  'package-manager': '📦 Package Managers',
  'editor':          '💙 Editors & IDEs',
  'cli':             '⚡ CLI & Development',
  'database':        '🗄️ Databases',
  'devops':          '🐳 DevOps & Containers',
  'testing':         '🧪 Testing & API',
  'web-server':      '🌐 Web Server (WampServer)',
  'system':          '🔧 System Libraries',
}
