import type { Tool } from '../shared/types'

export const tools: Tool[] = [
  // ── Version Control ────────────────────────────────────────────────────────
  {
    id: 'git',
    name: 'Git',
    description: 'Distributed version control system',
    category: 'version-control',
    platforms: ['windows', 'macos', 'linux'],
    version: '2.45+',
    size: '50 MB',
    icon: '🔀',
    verifyCommand: 'git --version',
    installers: {
      windows: 'installers/windows/install-git.ps1',
      macos: 'installers/macos/install-git.sh',
      linux: 'installers/linux/install-git.sh',
    },
  },
  {
    id: 'github-desktop',
    name: 'GitHub Desktop',
    description: 'Visual Git/GitHub interface',
    category: 'version-control',
    platforms: ['windows', 'macos'],
    version: '3.x',
    size: '150 MB',
    icon: '🖥️',
    verifyCommand: 'git --version',
    installers: {
      windows: 'installers/windows/install-github-desktop.ps1',
      macos: 'installers/macos/install-github-desktop.sh',
    },
  },
  {
    id: 'git-lfs',
    name: 'Git LFS',
    description: 'Large File Storage for Git',
    category: 'version-control',
    platforms: ['windows', 'macos', 'linux'],
    version: '3.4+',
    size: '40 MB',
    icon: '📦',
    verifyCommand: 'git lfs version',
    dependsOn: ['git'],
    installers: {
      windows: 'installers/windows/install-git-lfs.ps1',
      macos: 'installers/macos/install-git-lfs.sh',
      linux: 'installers/linux/install-git-lfs.sh',
    },
  },

  // ── Runtime & Languages ────────────────────────────────────────────────────
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'JavaScript/TypeScript runtime',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '20 LTS',
    size: '200 MB',
    icon: '🟢',
    verifyCommand: 'node --version',
    installers: {
      windows: 'installers/windows/install-nodejs.ps1',
      macos: 'installers/macos/install-nodejs.sh',
      linux: 'installers/linux/install-nodejs.sh',
    },
  },
  {
    id: 'python',
    name: 'Python',
    description: 'Python programming language',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '3.12+',
    size: '100 MB',
    icon: '🐍',
    verifyCommand: 'python --version',
    installers: {
      windows: 'installers/windows/install-python.ps1',
      macos: 'installers/macos/install-python.sh',
      linux: 'installers/linux/install-python.sh',
    },
  },
  {
    id: 'golang',
    name: 'Go Lang',
    description: 'Go programming language',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.21+',
    size: '300 MB',
    icon: '🐹',
    verifyCommand: 'go version',
    installers: {
      windows: 'installers/windows/install-golang.ps1',
      macos: 'installers/macos/install-golang.sh',
      linux: 'installers/linux/install-golang.sh',
    },
  },
  {
    id: 'rust',
    name: 'Rust',
    description: 'Rust programming language & Cargo',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.75+',
    size: '150 MB',
    icon: '🦀',
    verifyCommand: 'rustc --version',
    installers: {
      windows: 'installers/windows/install-rust.ps1',
      macos: 'installers/macos/install-rust.sh',
      linux: 'installers/linux/install-rust.sh',
    },
  },
  {
    id: 'deno',
    name: 'Deno',
    description: 'Modern TypeScript/JavaScript runtime',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.40+',
    size: '100 MB',
    icon: '🦕',
    verifyCommand: 'deno --version',
    installers: {
      windows: 'installers/windows/install-deno.ps1',
      macos: 'installers/macos/install-deno.sh',
      linux: 'installers/linux/install-deno.sh',
    },
  },
  {
    id: 'bun',
    name: 'Bun',
    description: 'Ultra-fast JavaScript runtime',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.0+',
    size: '80 MB',
    icon: '🍞',
    verifyCommand: 'bun --version',
    installers: {
      windows: 'installers/windows/install-bun.ps1',
      macos: 'installers/macos/install-bun.sh',
      linux: 'installers/linux/install-bun.sh',
    },
  },
  {
    id: 'java',
    name: 'Java (JDK)',
    description: 'Java Development Kit',
    category: 'runtime',
    platforms: ['windows', 'macos', 'linux'],
    version: '21.0+',
    size: '500 MB',
    icon: '☕',
    verifyCommand: 'java --version',
    installers: {
      windows: 'installers/windows/install-java.ps1',
      macos: 'installers/macos/install-java.sh',
      linux: 'installers/linux/install-java.sh',
    },
  },

  // ── Package Managers ───────────────────────────────────────────────────────
  {
    id: 'yarn',
    name: 'Yarn',
    description: 'Alternative Node.js package manager',
    category: 'package-manager',
    platforms: ['windows', 'macos', 'linux'],
    version: '4.0+',
    size: '30 MB',
    icon: '🧶',
    verifyCommand: 'yarn --version',
    dependsOn: ['nodejs'],
    installers: {
      windows: 'installers/windows/install-yarn.ps1',
      macos: 'installers/macos/install-yarn.sh',
      linux: 'installers/linux/install-yarn.sh',
    },
  },
  {
    id: 'maven',
    name: 'Maven',
    description: 'Java build & dependency manager',
    category: 'package-manager',
    platforms: ['windows', 'macos', 'linux'],
    version: '3.9+',
    size: '50 MB',
    icon: '🪶',
    verifyCommand: 'mvn --version',
    dependsOn: ['java'],
    installers: {
      windows: 'installers/windows/install-maven.ps1',
      macos: 'installers/macos/install-maven.sh',
      linux: 'installers/linux/install-maven.sh',
    },
  },
  {
    id: 'gradle',
    name: 'Gradle',
    description: 'Alternative Java build tool',
    category: 'package-manager',
    platforms: ['windows', 'macos', 'linux'],
    version: '8.5+',
    size: '100 MB',
    icon: '🐘',
    verifyCommand: 'gradle --version',
    dependsOn: ['java'],
    installers: {
      windows: 'installers/windows/install-gradle.ps1',
      macos: 'installers/macos/install-gradle.sh',
      linux: 'installers/linux/install-gradle.sh',
    },
  },
  {
    id: 'homebrew',
    name: 'Homebrew',
    description: 'macOS package manager',
    category: 'package-manager',
    platforms: ['macos'],
    version: '4.1+',
    size: '50 MB',
    icon: '🍺',
    verifyCommand: 'brew --version',
    installers: {
      macos: 'installers/macos/install-homebrew.sh',
    },
  },

  // ── Editors & IDEs ─────────────────────────────────────────────────────────
  {
    id: 'vscode',
    name: 'VSCode',
    description: 'Advanced & lightweight code editor',
    category: 'editor',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.87+',
    size: '350 MB',
    icon: '💙',
    verifyCommand: 'code --version',
    installers: {
      windows: 'installers/windows/install-vscode.ps1',
      macos: 'installers/macos/install-vscode.sh',
      linux: 'installers/linux/install-vscode.sh',
    },
  },

  // ── CLI & Development ──────────────────────────────────────────────────────
  {
    id: 'claude-cli',
    name: 'Claude CLI',
    description: 'Claude command-line interface',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '0.1+',
    size: '30 MB',
    icon: '🤖',
    verifyCommand: 'claude --version',
    dependsOn: ['nodejs'],
    installers: {
      windows: 'installers/windows/install-claude-cli.ps1',
      macos: 'installers/macos/install-claude-cli.sh',
      linux: 'installers/linux/install-claude-cli.sh',
    },
  },
  {
    id: 'codex-cli',
    name: 'Codex CLI',
    description: 'Codex integration CLI',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '1.0+',
    size: '25 MB',
    icon: '⚡',
    verifyCommand: 'codex --version',
    dependsOn: ['nodejs'],
    installers: {
      windows: 'installers/windows/install-codex-cli.ps1',
      macos: 'installers/macos/install-codex-cli.sh',
      linux: 'installers/linux/install-codex-cli.sh',
    },
  },
  {
    id: 'rtk',
    name: 'RTK',
    description: 'CLI proxy that reduces LLM token usage 60-90% on dev commands',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '0.39+',
    size: '4 MB',
    icon: '🦀',
    verifyCommand: 'rtk --version',
    brewId: 'rtk',
    installers: {
      windows: 'installers/windows/install-rtk.ps1',
      macos: 'installers/macos/install-rtk.sh',
      linux: 'installers/linux/install-rtk.sh',
    },
  },
  {
    id: 'github-cli',
    name: 'GitHub CLI',
    description: 'Official GitHub command-line tool',
    category: 'cli',
    platforms: ['windows', 'macos', 'linux'],
    version: '2.92+',
    size: '35 MB',
    icon: 'GH',
    verifyCommand: 'gh --version',
    dependsOn: ['git'],
    installers: {
      windows: 'installers/windows/install-github-cli.ps1',
      macos: 'installers/macos/install-github-cli.sh',
      linux: 'installers/linux/install-github-cli.sh',
    },
  },

  // ── Databases ──────────────────────────────────────────────────────────────
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    description: 'Advanced relational database',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '16.0+',
    size: '400 MB',
    icon: '🐘',
    verifyCommand: 'psql --version',
    installers: {
      windows: 'installers/windows/install-postgresql.ps1',
      macos: 'installers/macos/install-postgresql.sh',
      linux: 'installers/linux/install-postgresql.sh',
    },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'Document-oriented NoSQL database',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '7.0+',
    size: '500 MB',
    icon: '🍃',
    verifyCommand: 'mongod --version',
    installers: {
      windows: 'installers/windows/install-mongodb.ps1',
      macos: 'installers/macos/install-mongodb.sh',
      linux: 'installers/linux/install-mongodb.sh',
    },
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'In-memory cache/session database',
    category: 'database',
    platforms: ['windows', 'macos', 'linux'],
    version: '7.2+',
    size: '50 MB',
    icon: '🔴',
    verifyCommand: 'redis-cli --version',
    installers: {
      windows: 'installers/windows/install-redis.ps1',
      macos: 'installers/macos/install-redis.sh',
      linux: 'installers/linux/install-redis.sh',
    },
  },

  // ── DevOps & Containers ────────────────────────────────────────────────────
  {
    id: 'docker',
    name: 'Docker',
    description: 'Containerization platform',
    category: 'devops',
    platforms: ['windows', 'macos', 'linux'],
    version: '25.0+',
    size: '500 MB',
    icon: '🐳',
    verifyCommand: 'docker --version',
    installers: {
      windows: 'installers/windows/install-docker.ps1',
      macos: 'installers/macos/install-docker.sh',
      linux: 'installers/linux/install-docker.sh',
    },
  },
  {
    id: 'docker-compose',
    name: 'Docker Compose',
    description: 'Multi-container orchestration',
    category: 'devops',
    platforms: ['windows', 'macos', 'linux'],
    version: '2.25+',
    size: '50 MB',
    icon: '🐙',
    verifyCommand: 'docker compose version',
    dependsOn: ['docker'],
    installers: {
      windows: 'installers/windows/install-docker-compose.ps1',
      macos: 'installers/macos/install-docker-compose.sh',
      linux: 'installers/linux/install-docker-compose.sh',
    },
  },

  // ── Testing & API ──────────────────────────────────────────────────────────
  {
    id: 'postman',
    name: 'Postman',
    description: 'API testing & development platform',
    category: 'testing',
    platforms: ['windows', 'macos', 'linux'],
    version: '12.0+',
    size: '400 MB',
    icon: '📮',
    verifyCommand: 'postman --version',
    installers: {
      windows: 'installers/windows/install-postman.ps1',
      macos: 'installers/macos/install-postman.sh',
      linux: 'installers/linux/install-postman.sh',
    },
  },
]

export const categoryLabels: Record<string, string> = {
  'version-control': 'Version Control & Git',
  'runtime': 'Runtime & Languages',
  'package-manager': 'Package Managers',
  'editor': 'Editors & IDEs',
  'cli': 'CLI & Development',
  'database': 'Databases',
  'devops': 'DevOps & Containers',
  'testing': 'Testing & API',
}
